name: financier
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0+1
environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  freezed_annotation: ^3.0.0
  uuid: ^4.5.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  drift: ^2.25.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.31
  shared_preferences: ^2.5.2
  crypt: ^4.3.1
  pie_chart: ^5.4.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  connectivity_plus: ^6.1.3
  flex_color_scheme: ^8.1.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  in_app_purchase: ^3.2.1
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed:
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  drift_dev: ^2.25.2
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"